---
title: "Data Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(patchwork)
library(haven)
data <- read_sas("data/chs2017_public.sas7bdat")

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colur_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
data_clean = 
  data %>% 
  select(imputed_foodinsecure, toldhighbp17, diabetes17, weight17in4, currdepress, agegroup, sex, newrace) %>% 
  mutate(
    imputed_foodinsecure = recode(imputed_foodinsecure, 
              "1" = "No", 
              "2" = "No",
              "3" = "Yes",
              "4" = "Yes"),
    toldhighbp17 = recode(toldhighbp17,
                          "1" = "1",
                          "2" = "0"),
    toldhighbp17 = as.numeric(toldhighbp17),
    diabetes17 = recode(diabetes17,
                        "1" = "1",
                        "2" = "0"),
    diabetes17 = as.numeric(diabetes17),
    weight17in4 = recode(weight17in4,
                         "1" = "0",
                         "2" = "0",
                         "3" = "0",
                         "4" = "1"),
  weight17in4 = as.numeric(weight17in4),
    currdepress = recode(currdepress,
                         "1" = "1",
                         "2" = "0"),
  currdepress = as.numeric(currdepress),
    agegroup = recode(agegroup,
                      "1" = "18-24",
                      "2" = "25-44",
                      "3" = "45-64",
                      "4" = "65+"),
    sex = recode(sex, 
                 "1" = "Male",
                 "2" = "Female"),
    newrace = recode(newrace,
                     "1" = "White non-Hispanic",
                     "2" = "Black non-Hispanic",
                     "3" = "Hispanic",
                     "4" = "Asian/PI/non-Hispanic",
                     "5" = "Other non-Hispanic"),
  ) %>%  
  rename("Food_Insecure" = imputed_foodinsecure,
         "High_BP" = toldhighbp17,
         "Diabetes" = diabetes17,
         "Obesity" = weight17in4,
         "Depression" = currdepress,
         "Age" = agegroup,
         "Sex" = sex,
         "Race" = newrace) %>% 
  drop_na()
```

```{r}
##Creating five individual bar charts to represent the distribution of the outcomes against age and race.

plot1 = 
data_clean %>% 
  select(Age, Food_Insecure, Race) %>% 
  count(Age, Food_Insecure, Race) %>% 
  group_by(Age, Race) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Food_Insecure == "Yes") %>% 
  mutate(
    Total_Insecure = sum(n),
    Proportion = Total_Insecure / total)


plot1 %>% 
ggplot() +
  geom_col(aes(x = Age, y = Total_Insecure, fill = Race)) +
  labs(
    x = "Age Group",
    y = "Food Insecure Count",
    title = "Food Insecurity by Age and Race",
    caption = "Data from Community Health Survey (2017)"
  )

plot2 = 
data_clean %>% 
  select(Age, Obesity, Race) %>% 
  count(Age, Obesity, Race) %>% 
  group_by(Age, Race) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Obesity == "1") %>% 
  mutate(
    Total_Obese = sum(n),
    Proportion = Total_Obese / total)


plot2 %>% 
ggplot() +
  geom_col(aes(x = Age, y = Total_Obese, fill = Race)) +
  labs(
    x = "Age Group",
    y = "Obesity Count",
    title = "Obesity by Age and Race",
    caption = "Data from Community Health Survey (2017)"
  )

plot3 = 
data_clean %>% 
  select(Age, Diabetes, Race) %>% 
  count(Age, Diabetes, Race) %>% 
  group_by(Age, Race) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Diabetes == "1") %>% 
  mutate(
    Total_Diabetes = sum(n),
    Proportion = Total_Diabetes / total)


plot3 %>% 
ggplot() +
  geom_col(aes(x = Age, y = Total_Diabetes, fill = Race)) +
  labs(
    x = "Age Group",
    y = "Diabetes Count",
    title = "Diabetes by Age and Race",
    caption = "Data from Community Health Survey (2017)"
  )

plot4 = 
data_clean %>% 
  select(Age, High_BP, Race) %>% 
  count(Age, High_BP, Race) %>% 
  group_by(Age, Race) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(High_BP == "1") %>% 
  mutate(
    Total_High_BP = sum(n),
    Proportion = Total_High_BP / total)


plot4 %>% 
ggplot() +
  geom_col(aes(x = Age, y = Total_High_BP, fill = Race)) +
  labs(
    x = "Age Group",
    y = "High Blood Pressure Count",
    title = "High Blood Pressure by Age and Race",
    caption = "Data from Community Health Survey (2017)"
  )

plot5 = 
data_clean %>% 
  select(Age, Depression, Race) %>% 
  count(Age, Depression, Race) %>% 
  group_by(Age, Race) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Depression == "1") %>% 
  mutate(
    Total_Depress = sum(n),
    Proportion = Total_Depress / total)

plot5 %>% 
ggplot() +
  geom_col(aes(x = Age, y = Total_Depress, fill = Race)) +
  labs(
    x = "Age Group",
    y = "Depression Count",
    title = "Depression by Age and Race", 
    caption = "Data from Community Health Survey (2017)"
  )

```

```{r}
##Calculating the proportion of cases for each of the five outcomes, and overlaying the proportions in one figure.

Food_Insecure = 
data_clean %>% 
  select(Age, Food_Insecure) %>% 
  count(Age, Food_Insecure) %>% 
  group_by(Age) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Food_Insecure == "Yes") %>% 
  mutate(
    Total_Insecure = sum(n),
    Proportion = Total_Insecure / total)

Obesity = 
data_clean %>% 
  select(Age, Obesity) %>% 
  count(Age, Obesity) %>% 
  group_by(Age) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Obesity == "1") %>% 
  mutate(
    Total_Obese = sum(n),
    Proportion = Total_Obese / total)

Diabetes = 
data_clean %>% 
  select(Age, Diabetes) %>% 
  count(Age, Diabetes) %>% 
  group_by(Age) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Diabetes == "1") %>% 
  mutate(
    Total_Diabetes = sum(n),
    Proportion = Total_Diabetes / total)

High_BP = 
data_clean %>% 
  select(Age, High_BP) %>% 
  count(Age, High_BP) %>% 
  group_by(Age) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(High_BP == "1") %>% 
  mutate(
    Total_High_BP = sum(n),
    Proportion = Total_High_BP / total)

Depression = 
data_clean %>% 
  select(Age, Depression) %>% 
  count(Age, Depression) %>% 
  group_by(Age) %>% 
  mutate(
    total = sum(n)) %>% 
  filter(Depression == "1") %>% 
  mutate(
    Total_Depress = sum(n),
    Proportion = Total_Depress / total)

ggplot() +
  geom_line(data = Food_Insecure, (aes(x = Age, y = Proportion, group = 1, color = "Food Insecure"))) +
  geom_line(data = Obesity, (aes(x = Age, y = Proportion, group = 1, color = "Obesity"))) +
  geom_line(data = Diabetes, (aes(x = Age, y = Proportion, group = 1, color = "Diabetes"))) +
  geom_line(data = High_BP, (aes(x = Age, y = Proportion, group = 1, color = "High BP"))) +
  geom_line(data = Depression, (aes(x = Age, y = Proportion, group = 1, color = "Depression"))) +
  labs(
    title = "Proportion of Cases by Age Group",
    x = "Age Group",
    y = "Proportion",
    caption = "Data from Community Health Survey (2017)") 

```

```{r}
fit_logistic_obesity = 
  data_clean %>% 
  glm(Obesity ~ Food_Insecure + Age + Sex + Race, data = ., family = binomial())

fit_logistic_obesity %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit_logistic_High_BP = 
  data_clean %>% 
  glm(High_BP ~ Food_Insecure + Age + Sex + Race, data = ., family = binomial())

fit_logistic_High_BP %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit_logistic_Depression = 
  data_clean %>% 
  glm(Depression ~ Food_Insecure + Age + Sex + Race, data = ., family = binomial())

fit_logistic_Depression %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit_logistic_Diabetes = 
  data_clean %>% 
  glm(Diabetes ~ Food_Insecure + Age + Sex + Race, data = ., family = binomial())

fit_logistic_Diabetes %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)
```



